server:
  port: 8081
spring:
  neo4j:
    # 登录用户密码
    authentication:
      username: neo4j
      password: ht83336168!
    # neo4j服务器地址
    uri: bolt://10.0.0.56:7687
  data:
    neo4j:
      database: neo4j

#logging:
#  level:
#    org:
#      neo4j:
#        ogm:
#          request: DEBUG
